# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runecs < Formula
  desc "Effortlessly Execute One-Off Tasks and Database Migrations in Your ECS Cluster"
  homepage "https://github.com/meap/runecs"
  version "0.8.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meap/runecs/releases/download/v0.8.2/runecs_Darwin_x86_64.tar.gz"
      sha256 "a496f4d51386525918f36cedc1de6c58b883aef2218819530a7fd43fd91c74cd"

      def install
        bin.install "runecs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meap/runecs/releases/download/v0.8.2/runecs_Darwin_arm64.tar.gz"
      sha256 "a0aff654b426e8dab7a88b283bbbc6b0ea3589103e54e74e2dc32ba842a247c3"

      def install
        bin.install "runecs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/meap/runecs/releases/download/v0.8.2/runecs_Linux_x86_64.tar.gz"
      sha256 "7487ee48fc1cd4fb87fc40c563d9510cd68ef24248670f42a7b648364f894a9b"
      def install
        bin.install "runecs"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/meap/runecs/releases/download/v0.8.2/runecs_Linux_armv6.tar.gz"
      sha256 "97244dab9c6e5d619450221185298d0bc8be3c82a69bc57c562e3fd85b2a9a45"
      def install
        bin.install "runecs"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/meap/runecs/releases/download/v0.8.2/runecs_Linux_arm64.tar.gz"
      sha256 "8b59239599fc74a854fddc07ddf8d3599922a3750940e3f6783800315b456e3e"
      def install
        bin.install "runecs"
      end
    end
  end
end
