# This file was generated by GoReleaser. DO NOT EDIT.
cask "runecs" do
  version "0.10.0"

  on_macos do
    on_intel do
      url "https://github.com/meap/runecs/releases/download/v#{version}/runecs_Darwin_x86_64.tar.gz"
      sha256 "0c67743c3661b101929bddc918cd90b0f7e1b8ebbbcee6cf6ef339d08732fe1e"
    end
    on_arm do
      url "https://github.com/meap/runecs/releases/download/v#{version}/runecs_Darwin_arm64.tar.gz"
      sha256 "390e02515ae608293002a3f9ddb4bcc648f64e3a08690307b80822ae566ce3ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/meap/runecs/releases/download/v#{version}/runecs_Linux_x86_64.tar.gz"
      sha256 "3f2375925bb98d5191a11a8f29f7a3d25452dca58a52a9fab8f334b85df66c73"
    end
    on_arm do
      url "https://github.com/meap/runecs/releases/download/v#{version}/runecs_Linux_arm64.tar.gz"
      sha256 "3859e0324a72a7cea070a6c53fc0287d2a947fb9dc1a57311da12b6bf6b45f57"
    end
  end

  name "runecs"
  desc "Effortlessly Execute One-Off Tasks and Database Migrations in Your ECS Cluster"
  homepage "https://github.com/meap/runecs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runecs"

  # No zap stanza required

end
